name=input("enter your name")
s1=int(input("enter your marks"))
s2=int(input("enter your marks"))
s3=int(input("enter your marks"))
s4=int(input("enter your marks"))
s5=int(input("enter your marks"))
print(f"marks are{s1+s2+s3+s4+s5},and avg is{s1+s2+s3+s4+s5}/5")
